export const SITE = {
  name: "MartX BD",
  tagline: "Premium Garments Buying House",
  description:
    "World-class apparel sourcing and garments buying house based in Bangladesh. Serving global fashion brands with ethical manufacturing and premium quality.",
  url: "https://www.martxbd.com",
  email: "info@martxbd.com",
  phone: "+880-1800-000000",
  whatsapp: "8801800000000",
  address: "House 12, Road 4, Sector 3, Uttara, Dhaka-1230, Bangladesh",
  social: {
    facebook: "https://facebook.com/martxbd",
    instagram: "https://instagram.com/martxbd",
    linkedin: "https://linkedin.com/company/martxbd",
    twitter: "https://twitter.com/martxbd",
    youtube: "https://youtube.com/@martxbd",
  },
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Products", href: "/products" },
  { label: "Compliance", href: "/compliance" },
  { label: "Sustainability", href: "/sustainability" },
  { label: "Gallery", href: "/gallery" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const STATS = [
  { value: "50+", label: "Partner Factories" },
  { value: "25+", label: "Export Countries" },
  { value: "2M+", label: "Monthly Production" },
  { value: "98%", label: "On-Time Shipment" },
];

export const HERO_SLIDES = [
  {
    headline: "Global Apparel Sourcing",
    subheadline: "Partner From Bangladesh",
    description:
      "Connecting world-class fashion brands with Bangladesh's finest garment manufacturers. Quality, compliance, and confidence — delivered.",
    image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1920&q=80",
  },
  {
    headline: "Ethical Manufacturing.",
    subheadline: "Premium Quality.",
    description:
      "We partner only with BSCI, SEDEX, and GOTS certified factories. Your supply chain, our responsibility.",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1920&q=80",
  },
  {
    headline: "From Fabric To",
    subheadline: "Final Shipment.",
    description:
      "End-to-end garment sourcing, production monitoring, quality assurance, and export logistics — all under one roof.",
    image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=1920&q=80",
  },
  {
    headline: "Premium Garment",
    subheadline: "Export Solutions.",
    description:
      "From T-shirts to tailored blazers, knitwear to denim — we source every category with precision and care.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1920&q=80",
  },
];

export const SERVICES = [
  {
    id: 1,
    title: "Product Development",
    description: "Understanding buyer requirements, creating samples and tech packs, custom sizing and fabric sourcing.",
    icon: "Layers",
    category: "Development",
  },
  {
    id: 2,
    title: "Apparel Sourcing",
    description: "Strategic sourcing of all garment categories from Bangladesh's top-tier certified manufacturers.",
    icon: "Search",
    category: "Sourcing",
  },
  {
    id: 3,
    title: "Fabric & Trim Sourcing",
    description: "Premium fabric and trim sourcing from China, Bangladesh, and India — yarn, cotton, polyester, denim.",
    icon: "Scissors",
    category: "Sourcing",
  },
  {
    id: 4,
    title: "Merchandising",
    description: "Expert merchandising management ensuring seamless coordination between buyers and manufacturers.",
    icon: "ClipboardList",
    category: "Management",
  },
  {
    id: 5,
    title: "Sampling Development",
    description: "Rapid prototype sampling with precise adherence to specifications, fit, and finish requirements.",
    icon: "Package",
    category: "Development",
  },
  {
    id: 6,
    title: "Factory Sourcing",
    description: "Identifying and vetting the best-matched certified factory for your specific product requirements.",
    icon: "Building2",
    category: "Sourcing",
  },
  {
    id: 7,
    title: "Compliance Management",
    description: "Full compliance oversight covering BSCI, SEDEX, WRAP, OEKO-TEX, and GOTS certifications.",
    icon: "ShieldCheck",
    category: "Compliance",
  },
  {
    id: 8,
    title: "Production Monitoring",
    description: "Real-time production tracking with dedicated merchandisers on the factory floor.",
    icon: "Activity",
    category: "Production",
  },
  {
    id: 9,
    title: "Quality Assurance (QA)",
    description: "Systematic quality assurance throughout the entire production lifecycle.",
    icon: "CheckCircle",
    category: "Quality",
  },
  {
    id: 10,
    title: "Quality Control (QC)",
    description: "In-line, pre-final, and final QC inspections ensuring every shipment meets buyer standards.",
    icon: "Eye",
    category: "Quality",
  },
  {
    id: 11,
    title: "Inline Inspection",
    description: "Proactive quality intervention during production to catch defects before they multiply.",
    icon: "Scan",
    category: "Quality",
  },
  {
    id: 12,
    title: "Final Random Inspection",
    description: "AQL-based final random inspection before shipment — zero compromise on quality.",
    icon: "ScanLine",
    category: "Quality",
  },
  {
    id: 13,
    title: "Lab Testing",
    description: "Certified lab testing for colorfastness, shrinkage, tensile strength, and chemical compliance.",
    icon: "FlaskConical",
    category: "Testing",
  },
  {
    id: 14,
    title: "Supply Chain Management",
    description: "End-to-end supply chain visibility and optimization for predictable, efficient production.",
    icon: "Network",
    category: "Logistics",
  },
  {
    id: 15,
    title: "Logistics & Shipment",
    description: "Expert logistics coordination for sea and air freight with full documentation support.",
    icon: "Ship",
    category: "Logistics",
  },
  {
    id: 16,
    title: "Export Documentation",
    description: "Complete export documentation including customs, LC, certificates of origin, and more.",
    icon: "FileText",
    category: "Logistics",
  },
  {
    id: 17,
    title: "Vendor Management",
    description: "Strategic vendor relationships built on performance, compliance, and mutual growth.",
    icon: "Users",
    category: "Management",
  },
  {
    id: 18,
    title: "Costing & Negotiation",
    description: "Competitive costing and skilled negotiation to maximize your margin without compromising quality.",
    icon: "Calculator",
    category: "Commercial",
  },
  {
    id: 19,
    title: "Tech Pack Development",
    description: "Detailed technical package creation including construction sheets, grading, and BOM.",
    icon: "FileCode",
    category: "Development",
  },
  {
    id: 20,
    title: "Sustainable Sourcing",
    description: "Eco-conscious sourcing with verified sustainable fabrics, recycled materials, and green factories.",
    icon: "Leaf",
    category: "Sustainability",
  },
  {
    id: 21,
    title: "Private Label Manufacturing",
    description: "Custom private label production with full brand ownership — from concept to finished product.",
    icon: "Tag",
    category: "Manufacturing",
  },
  {
    id: 22,
    title: "Trend Research",
    description: "Global fashion trend intelligence to keep your collections commercially relevant and competitive.",
    icon: "TrendingUp",
    category: "Development",
  },
];

export const PRODUCT_CATEGORIES = [
  {
    title: "T-Shirts",
    description: "100% cotton, blended, and sustainable tees in every weight and style.",
    image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=800&q=80",
    moq: "500 pcs",
    leadTime: "30-45 days",
  },
  {
    title: "Polo Shirts",
    description: "Premium piqué and performance polo shirts for retail and corporate markets.",
    image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800&q=80",
    moq: "300 pcs",
    leadTime: "35-50 days",
  },
  {
    title: "Denim",
    description: "Fashion denim jeans, jackets, and shorts in stretch and rigid fabrics.",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80",
    moq: "500 pcs",
    leadTime: "45-60 days",
  },
  {
    title: "Jackets",
    description: "Woven and knit outerwear jackets from lightweight bombers to padded winter coats.",
    image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=800&q=80",
    moq: "200 pcs",
    leadTime: "50-65 days",
  },
  {
    title: "Sweaters",
    description: "Premium knitwear sweaters in wool, cashmere, cotton, and synthetic blends.",
    image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&q=80",
    moq: "300 pcs",
    leadTime: "45-60 days",
  },
  {
    title: "Hoodies & Sweatshirts",
    description: "Fleece, French terry, and loopback hoodies for all market segments.",
    image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80",
    moq: "300 pcs",
    leadTime: "35-50 days",
  },
  {
    title: "Sportswear",
    description: "High-performance activewear in moisture-wicking, compression, and recycled fabrics.",
    image: "https://images.unsplash.com/photo-1539710094548-57f55d0a20eb?w=800&q=80",
    moq: "500 pcs",
    leadTime: "40-55 days",
  },
  {
    title: "Workwear & Uniforms",
    description: "Durable corporate and industrial workwear with custom branding and logos.",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
    moq: "200 pcs",
    leadTime: "30-45 days",
  },
];

export const CERTIFICATIONS = [
  { name: "BSCI", description: "Business Social Compliance Initiative", color: "#1a73e8" },
  { name: "SEDEX", description: "Supplier Ethical Data Exchange", color: "#0f9d58" },
  { name: "WRAP", description: "Worldwide Responsible Apparel Production", color: "#e53935" },
  { name: "OEKO-TEX", description: "International textile safety certification", color: "#1565c0" },
  { name: "GOTS", description: "Global Organic Textile Standard", color: "#2e7d32" },
  { name: "Accord", description: "Bangladesh Accord on Fire and Building Safety", color: "#f57c00" },
  { name: "RSC", description: "Remediation Sustainability Council", color: "#6a1b9a" },
];

export const WORKFLOW_STEPS = [
  { step: "01", title: "Inquiry", description: "Submit your product requirements, specifications, and target pricing." },
  { step: "02", title: "Costing", description: "We provide competitive costing with full cost breakdown transparency." },
  { step: "03", title: "Sampling", description: "Proto and fit samples developed with precise spec adherence." },
  { step: "04", title: "Approval", description: "Buyer approves samples and confirms production order details." },
  { step: "05", title: "Production", description: "Manufacturing begins with dedicated merchandiser oversight." },
  { step: "06", title: "QC Inspection", description: "Inline and final AQL-based quality inspection at factory." },
  { step: "07", title: "Packaging", description: "Export-grade packaging with labeling per buyer requirements." },
  { step: "08", title: "Shipment", description: "Sea or air freight with complete export documentation." },
];

export const WHY_CHOOSE_US = [
  { title: "Competitive Pricing", description: "Direct factory relationships mean we negotiate the best price without compromising quality.", icon: "DollarSign" },
  { title: "Ethical Factories", description: "100% of our partner factories hold international compliance certifications.", icon: "ShieldCheck" },
  { title: "Strict Quality Control", description: "Multi-stage QC inspection with AQL standards at every production milestone.", icon: "CheckSquare" },
  { title: "On-Time Delivery", description: "98% on-time shipment rate backed by proactive production monitoring.", icon: "Clock" },
  { title: "Real-Time Updates", description: "Live production dashboards and weekly reports keep you fully informed.", icon: "Activity" },
  { title: "Experienced Team", description: "25+ years combined experience in Bangladesh garments and apparel sourcing.", icon: "Users" },
  { title: "Dedicated QA Team", description: "In-house quality assurance team stationed at every partner factory.", icon: "Eye" },
  { title: "Strong Supply Chain", description: "Resilient, diversified supply chain across 50+ vetted factories.", icon: "Network" },
  { title: "Transparent Communication", description: "Single point of contact, real-time messaging, and no hidden charges.", icon: "MessageSquare" },
];

export const EXPORT_COUNTRIES = [
  { country: "United States", code: "US", flag: "🇺🇸" },
  { country: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { country: "Germany", code: "DE", flag: "🇩🇪" },
  { country: "France", code: "FR", flag: "🇫🇷" },
  { country: "Spain", code: "ES", flag: "🇪🇸" },
  { country: "Italy", code: "IT", flag: "🇮🇹" },
  { country: "Netherlands", code: "NL", flag: "🇳🇱" },
  { country: "Canada", code: "CA", flag: "🇨🇦" },
  { country: "Australia", code: "AU", flag: "🇦🇺" },
  { country: "UAE", code: "AE", flag: "🇦🇪" },
  { country: "Sweden", code: "SE", flag: "🇸🇪" },
  { country: "Denmark", code: "DK", flag: "🇩🇰" },
  { country: "Japan", code: "JP", flag: "🇯🇵" },
  { country: "South Korea", code: "KR", flag: "🇰🇷" },
];

export const TESTIMONIALS = [
  {
    name: "James Mitchell",
    title: "Head of Sourcing",
    company: "Global Fashion Group",
    quote: "MartX BD has been our trusted sourcing partner for 5 years. Their QC team is exceptional, and they consistently deliver on time. Highly professional organization.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
  },
  {
    name: "Sarah Hoffmann",
    title: "VP of Procurement",
    company: "EuroStyle GmbH",
    quote: "The level of transparency and communication from MartX BD is unlike any other supplier we've worked with. They truly operate as a strategic partner.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  },
  {
    name: "David Chen",
    title: "CEO",
    company: "Pacific Apparel Co.",
    quote: "Outstanding quality, competitive pricing, and a team that genuinely cares about getting it right. MartX BD sets the standard for buying house operations.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    name: "Emma Larsson",
    title: "Sustainability Director",
    company: "Nordic Fashion AB",
    quote: "Their commitment to ethical manufacturing and sustainability aligns perfectly with our brand values. The GOTS certified supply chain gives us complete peace of mind.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
  {
    name: "Marco Rossi",
    title: "Buying Director",
    company: "Mediterraneo Fashion",
    quote: "From sampling to final shipment, the entire process is seamless. MartX BD's attention to detail and proactive communication makes them our number one sourcing partner.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: "Bangladesh RMG Sector: 2025 Growth Outlook and Opportunities",
    excerpt: "Bangladesh's ready-made garment industry continues to grow as global brands seek ethical, cost-effective manufacturing alternatives.",
    category: "Industry News",
    date: "2025-05-10",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&q=80",
    slug: "bangladesh-rmg-2025-growth",
    author: "Rafiq Ahmed",
    authorRole: "Head of Sourcing",
    authorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    id: 2,
    title: "Sustainable Sourcing: How Buying Houses Are Leading the Green Revolution",
    excerpt: "From organic cotton to recycled polyester, the shift toward sustainable apparel sourcing is reshaping Bangladesh's garment industry.",
    category: "Sustainability",
    date: "2025-04-28",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    slug: "sustainable-sourcing-green-revolution",
    author: "Nadia Islam",
    authorRole: "Sustainability Lead",
    authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  },
  {
    id: 3,
    title: "The Importance of AQL Inspection in Garment Quality Control",
    excerpt: "Understanding AQL standards and why rigorous inspection protocols are non-negotiable for export-quality garments.",
    category: "Quality Control",
    date: "2025-04-15",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    slug: "aql-inspection-quality-control",
    author: "Kamrul Hasan",
    authorRole: "QC Manager",
    authorImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
  },
  {
    id: 4,
    title: "BSCI vs SEDEX: Which Compliance Framework Is Right for Your Supply Chain?",
    excerpt: "A comprehensive comparison of the two most widely recognized social compliance frameworks in the global garment industry.",
    category: "Compliance",
    date: "2025-04-02",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
    slug: "bsci-vs-sedex-comparison",
    author: "Tasnim Akter",
    authorRole: "Compliance Officer",
    authorImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
  {
    id: 5,
    title: "Tech Pack Development: The Foundation of Successful Garment Production",
    excerpt: "Why a well-structured technical package is essential for accurate sampling, costing, and defect-free production.",
    category: "Product Development",
    date: "2025-03-20",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=800&q=80",
    slug: "tech-pack-development-guide",
    author: "Mahmud Hossain",
    authorRole: "Product Development",
    authorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
  },
  {
    id: 6,
    title: "Knitwear Manufacturing in Bangladesh: A Global Leader's Edge",
    excerpt: "Bangladesh's knitwear sector has emerged as a dominant force in global apparel exports, offering unmatched value.",
    category: "Manufacturing",
    date: "2025-03-08",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&q=80",
    slug: "knitwear-manufacturing-bangladesh",
    author: "Rafiq Ahmed",
    authorRole: "Head of Sourcing",
    authorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
];
